apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-autoscaler
  labels:
    k8s-app: nginx-autoscaler
spec:
  selector:
    matchLabels:
      k8s-app: nginx-autoscaler
  template:
    metadata:
      labels:
        k8s-app: nginx-autoscaler
    spec:
      serviceAccountName: zyh
      containers:
      - name: autoscaler
        image: mirrorgooglecontainers/cluster-proportional-autoscaler-amd64:1.6.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 20m
            memory: 10Mi
        command:
        - /cluster-proportional-autoscaler
        - --namespace=default
        - --configmap=nginx-autoscaler
        - --target=deployment/nginx
        # When cluster is using large nodes(with more cores), "coresPerReplica" should dominate.
        # If using small nodes, "nodesPerReplica" should dominate.
        - --default-params={"linear":{"coresPerReplica":4,"nodesPerReplica":16,"min":1}}
        - --logtostderr=true
        - --v=2
