apiVersion: v1
kind: ConfigMap
metadata:
  name: tmp-cm
data:
  nginx.conf: |
    user  nginx;
    worker_processes  4;
    worker_rlimit_nofile 48127;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;    
    events {
        multi_accept        on;
        worker_connections  16384;
        use                 epoll;
    }    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
    
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';    
        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        #tcp_nopush     on;
        keepalive_timeout  65;
        #gzip  on;
        #include /etc/nginx/conf.d/*.conf;
        server {
          listen       80;
          server_name  localhost;
          location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
          }
          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
              root   /usr/share/nginx/html;
          }
          location /nginx_status {
              #allow 127.0.0.1;
              #deny all;
              access_log off;
              stub_status on;
          }
        }
    } 

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tmp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tmp
    spec:
      nodeSelector:
        kubernetes.io/hostname: 192.168.5.86
      containers:
        - name: tmp
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: tmp-config
              subPath: etc/nginx/nginx.conf
          ports:
            - containerPort: 80
      volumes:
        - name: tmp-config
          configMap:
            name: tmp-cm
            items:
            - key: nginx.conf
              path: etc/nginx/nginx.conf
