apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: burn-memory
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "app": "memory"
  stressors:
    memory:
      workers: 1
  duration: "55s"
  scheduler:
    cron: "@every 1m"
