{
 "title": "memory",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": "label_values(node_uname_info{}, kubernetes_node)"
   }
  ]
 },
 "panels": [
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{kubernetes_node=\"$node\"}",
     "legendFormat": "1分钟负载"
    },
    {
     "expr": "node_load5{kubernetes_node=\"$node\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "node_load15{kubernetes_node=\"$node\"}",
     "legendFormat": "15分钟负载"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{kubernetes_node=~\"$node\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU总核数"
    }
   ]
  },
  {
   "title": "$node-pod-memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"$node\"}) by (pod)",
     "legendFormat": "{{pod-name}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"$node\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "节点内存使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"$node\"}) / sum( node_memory_MemTotal_bytes{kubernetes_node=~\"$node\"}  - 1048576000 ) * 100"
    }
   ]
  },
  {
   "title": "已用内存总量",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"$node\"})"
    }
   ]
  },
  {
   "title": "可分配内存总量",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{kubernetes_node=~\"$node\"} - 1048576000 )"
    }
   ]
  },
  {
   "title": "$node-cpu",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"$node\"}[2m])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"$node\"}[2m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "节点CPU使用率",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (kubernetes_io_hostname) (irate(node_cpu_seconds_total{kubernetes_node=~\"$node\",mode=\"idle\"}[2m])) * 100)\n"
    }
   ]
  },
  {
   "title": "$node-memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_node=~\"$node\"}",
     "legendFormat": "总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_node=~\"$node\"} - node_memory_MemAvailable_bytes{kubernetes_node=~\"$node\"}",
     "legendFormat": "已用"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{kubernetes_node=~\"$node\"}",
     "legendFormat": "可用"
    },
    {
     "expr": "node_memory_Active_bytes{kubernetes_node=~\"$node\"}",
     "legendFormat": "活动"
    },
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_node=~\"$node\"} - node_memory_Active_bytes{kubernetes_node=~\"$node\"}",
     "legendFormat": "有效"
    }
   ]
  }
 ]
}