---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-ext
  labels:
    app: httpbin-ext
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 8888
  selector:
    app: httpbin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
      annotations:
        prometheus.io/scrape: "false"
        imageregistry: "http://hub.docker.com/22"
    spec:
      priorityClassName: high-priority
      nodeSelector:
        kubernetes.io/hostname: 10.2.2.121
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        command: ["gunicorn", "--access-logfile", "-", "-b", "0.0.0.0:8080", "httpbin:app"]
        env:
         - name: test
           value: "2"
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 800m
