apiVersion: apps/v1
kind: Deployment
metadata:
  name: test3
  labels:
    app: test3
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: test3
  template:
    metadata:
      labels:
        app: test3
    spec:
      nodeSelector:
        test: memory
      containers:
      - name: memory
        image: koza/memory:latest
        imagePullPolicy: IfNotPresent
        command: ["python2","start.py","50"]

