apiVersion: v1
kind: Pod
metadata:
  name: unpri-pod
  namespace: default
spec:
  nodeSelector:
    test: memory
  containers:
    - command: ['sh', '-c', 'echo "Hello, wwww.chenshaowen.com !" && sleep 3600']
      image: docker.io/alpine:3.12
      name: pod-test

