apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: n1
spec:
  hosts:
  - "n1.ng.com"
  gateways:
  - nginx-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: nginx-1
