---
apiVersion: x.getambassador.io/v3alpha1
kind: AmbassadorListener
metadata:
  name: http-listener-8888
spec:
  port: 8888
  protocol: HTTP  # NOT A TYPO, see below
  securityModel: XFP
  hostBinding:
    namespace:
      from: SELF   # See below
---
apiVersion: x.getambassador.io/v3alpha1
kind: AmbassadorListener
metadata:
  name: https-listener-9999
spec:
  port: 9999
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: SELF   # See below
---
apiVersion: getambassador.io/v2
kind:  TLSContext
metadata:
  name:  h2-tls-tmp
spec:
  secret: h2-certs
  hosts: ["*"]
  alpn_protocols: h2, http/1.1
---
apiVersion: x.getambassador.io/v3alpha1
kind: AmbassadorHost
metadata:
  name: tmp.com-host
spec:
  hostname: "*.tmp.com"
  acmeProvider:
    authority: none
  tlsSecret:
    name: h2-tls-tmp
  tlsSecret: 
    name: tls-cert
  requestPolicy:
    insecure:
      action: Route
---
apiVersion: x.getambassador.io/v3alpha1
kind:  AmbassadorMapping
metadata:
  name:  h9-mapping
spec:
  prefix: /
  service: nginx:80
  host: h9.tmp.com
